apiVersion: v1
entries:
  ibm-cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: 2020-02-19T07:29:41.620314-05:00
    description: Service for issuing and managing certificates on IBM Cloud Private.
    digest: bfc3d3fc52c1605dbbd4043742aae37859d04ff7b3bcdee98384752472d060a2
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - ICP
    - IcpClusterResource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - IBM Cloud Private
    - ICPRHOCP
    - RHOCP
    - ROKS
    - ICPROKS
    kubeVersion: '>=1.11.0'
    name: ibm-cert-manager
    tillerVersion: '>=2.7.0'
    urls:
    - https://raw.githubusercontent.com/open-cluster-management/multicloudhub-repo/master/multicloudhub/charts/ibm-cert-manager-3.5.0.tgz
    version: 3.5.0
  ibm-mcm-kui:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2020-02-19T07:29:41.620933-05:00
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: d8832d8e7794b225cda918e7062fef81788c69adb4c0199e77c156d0b6f3c45d
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: ibm-mcm-kui
    tillerVersion: '>=2.12.3'
    urls:
    - https://raw.githubusercontent.com/open-cluster-management/multicloudhub-repo/master/multicloudhub/charts/ibm-mcm-kui-3.5.0.tgz
    version: 3.5.0
  ibm-mcm-prod:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2020-02-19T07:29:41.625921-05:00
    description: IBM Multicloud Manager
    digest: e496492828e01af735297cb3b98f6b463a5b2307e1278d5a9cf717d463612ead
    keywords:
    - ICP
    - Analytics
    - Commercial
    - deploy
    - amd64
    kubeVersion: '>=1.14.0'
    name: ibm-mcm-prod
    tillerVersion: '>=2.9.1'
    urls:
    - https://raw.githubusercontent.com/open-cluster-management/multicloudhub-repo/master/multicloudhub/charts/ibm-mcm-prod-3.5.0.tgz
    version: 3.5.0
  ibm-search-prod:
  - appVersion: 3.4.0
    created: 2020-02-19T07:29:41.626775-05:00
    description: Search Helm Chart for IBM Cloud Pak for Multicloud Management
    digest: 600764ef01d70276288c4b2546fa19e18a2f4507bf5c0d034a9d3e84a73644d2
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicluster
    - search
    - Commercial
    - amd64
    - ppc64le
    - s390x
    - runtime
    kubeVersion: '>=1.10.0'
    name: ibm-search-prod
    tillerVersion: '>=2.9.0'
    urls:
    - https://raw.githubusercontent.com/open-cluster-management/multicloudhub-repo/master/multicloudhub/charts/ibm-search-prod-3.5.0.tgz
    version: 3.5.0
  icp-mongodb:
  - appVersion: 4.0.12
    created: 2020-02-19T07:29:41.628484-05:00
    description: NoSQL document-oriented database.
    digest: 88bfd00c104bac53830e80ea0f0ae248358bed554dae72ba909b3973166a4926
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    - database
    - ICP
    kubeVersion: '>=1.9.0-0'
    name: icp-mongodb
    sources:
    - https://github.com/mongodb/mongo
    tillerVersion: '>=2.9.0'
    urls:
    - https://raw.githubusercontent.com/open-cluster-management/multicloudhub-repo/master/multicloudhub/charts/icp-mongodb-3.4.2.tgz
    version: 3.4.2
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2020-02-19T07:29:41.629185-05:00
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: 32b1a937f29ef39c06332e612eeccaef75b349fcd89b1e20a91613b5a928b54c
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    tillerVersion: '>=2.12.3'
    urls:
    - https://raw.githubusercontent.com/open-cluster-management/multicloudhub-repo/master/multicloudhub/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  nginx:
  - apiVersion: v1
    appVersion: 1.16.1
    created: 2020-02-19T07:29:41.629861-05:00
    description: Chart for the nginx server
    digest: 4f714f3d19d34137334d293f85a761246fad985ce40401397bc2df79165626ca
    engine: gotpl
    home: http://www.nginx.org
    icon: https://bitnami.com/assets/stacks/nginx/img/nginx-stack-220x234.png
    keywords:
    - nginx
    - http
    - web
    - www
    - reverse proxy
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    name: nginx
    sources:
    - https://github.com/bitnami/bitnami-docker-nginx
    urls:
    - https://raw.githubusercontent.com/open-cluster-management/multicloudhub-repo/master/multicloudhub/charts/nginx-5.1.5.tgz
    version: 5.1.5
generated: 2020-02-19T07:29:41.616808-05:00
