apiVersion: v1
entries:
  application-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-19T19:51:03.500372623Z"
    description: Helm chart for Open Cluster Management application UI
    digest: 1d1c619ba20a1909015740e186dc67c46d716e354fa5f723d817be2459357198
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: application-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/application-chart-1.0.0.tgz
    version: 1.0.0
  cert-manager:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-19T19:51:03.505296987Z"
    dependencies:
    - alias: crd
      condition: cert-manager-crd.enabled
      name: cert-manager-crd
      repository: file://cert-manager-crd
      version: 3.4.0
    description: Service for issuing and managing certificates.
    digest: 00c215980222dbd0780d0b317ce2d5f960ed3225acfab1cd5a4b82afd543cc71
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-3.5.0.tgz
    version: 3.5.0
  cert-manager-no-crds:
  - apiVersion: v1
    appVersion: 3.5.0
    created: "2020-03-19T19:51:03.506210396Z"
    description: Service for issuing and managing certificates.
    digest: f7ea3419194eb053d2e498a6b63c63d16e92de6e31cf0890c41457ec4ed74ee5
    keywords:
    - amd64
    - ppc64le
    - s390x
    - OpenSource
    - Security
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - RHOCP
    - ROKS
    kubeVersion: '>=1.11.0'
    name: cert-manager-no-crds
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-no-crds-3.5.0.tgz
    version: 3.5.0
  cert-manager-webhook:
  - apiVersion: v1
    appVersion: 0.10.1
    created: "2020-03-19T19:51:03.507492453Z"
    description: A Helm chart for deploying the cert-manager webhook component
    digest: c278a15207c811da4c00e9d0b940d9f178ff49c3e52ab75c36f9864a49038ad7
    home: https://github.com/jetstack/cert-manager
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    - Development
    - amd64
    - ppc64le
    - s390x
    - Commercial
    - RHOCP
    kubeVersion: '>=1.9.0-0'
    name: cert-manager-webhook
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - http://multiclusterhub-repo:3000/charts/cert-manager-webhook-3.5.0.tgz
    version: 3.5.0
  configmap-watcher:
  - apiVersion: v1
    appVersion: 3.3.1
    created: "2020-03-19T19:51:03.508206721Z"
    description: A helm chart for deploying the config map watcher component.
    digest: 398053ec079e1c6770b53f6d8a96f00bb8f6ab14d60a3612b1ed84478c6ddb00
    keywords:
    - configmap
    - watcher
    - kubernetes
    - ICP
    - amd64
    - s390x
    - ppc64le
    - Tools
    - Development
    - Tech
    kubeVersion: '>=1.11.0'
    name: configmap-watcher
    urls:
    - http://multiclusterhub-repo:3000/charts/configmap-watcher-3.4.1.tgz
    version: 3.4.1
  console-chart:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-19T19:51:03.50899085Z"
    dependencies:
    - alias: crd
      name: console-crd
      repository: file://console-crd
      version: 1.0.0
    description: Helm chart for Open Cluster Management console UI
    digest: b05a62298a474d629822d53ffd46572d7b84400bba6ecb33be9b8d4344920f9e
    keywords:
    - ui
    kubeVersion: '>=1.10.0'
    name: console-chart
    urls:
    - http://multiclusterhub-repo:3000/charts/console-chart-1.0.0.tgz
    version: 1.0.0
  grc:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-19T19:51:03.509480559Z"
    description: helm chart for multicloud grc
    digest: b12fa30be792528456c1bcb6b016a569563ac09fc0f4dc1d40c83872b979516f
    keywords:
    - mcm
    - grc
    kubeVersion: '>=1.10.0'
    name: grc
    urls:
    - http://multiclusterhub-repo:3000/charts/grc-1.0.0.tgz
    version: 1.0.0
  kui-web-terminal:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-19T19:51:03.510220012Z"
    description: A helm chart for deploying the IBM Visual Web Terminal
    digest: a2defe8a40813bf24486811c8b827bcf18c14180cbde93bb46542601a179f551
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: kui-web-terminal
    urls:
    - http://multiclusterhub-repo:3000/charts/kui-web-terminal-3.5.0.tgz
    version: 3.5.0
  management-ingress:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-19T19:51:03.511108542Z"
    description: Multi Cloud control plane ingress controller
    digest: bb5aaf48a5e9843c6a2b19909aa7ddf348a5195df1c54ef319b4677643d41648
    keywords:
    - ingress
    - nginx
    - Network
    - Commercial
    - Limited
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: management-ingress
    urls:
    - http://multiclusterhub-repo:3000/charts/management-ingress-3.4.0.tgz
    version: 3.4.0
  multicluster-mongodb:
  - apiVersion: v1
    appVersion: 3.6.3
    created: "2020-03-20T00:58:03.320980964-07:00"
    description: NoSQL document-oriented database.
    digest: d3ca6d0837f070ffff3a493405da82cba72b0bcc1afc2c378bf353e8b05cca0e
    home: https://github.com/mongodb/mongo
    icon: https://webassets.mongodb.com/_com_assets/cms/mongodb-logo-rgb-j6w271g1xn.jpg
    keywords:
    - Commercial
    - Limited
    - amd64
    - database
    kubeVersion: '>=1.9.0-0'
    name: multicluster-mongodb
    sources:
    - https://github.com/mongodb/mongo
    urls:
    - http://multiclusterhub-repo:3000/charts/multicluster-mongodb-3.5.0.tgz
    version: 3.5.0
  rcm:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-03-19T19:51:03.516292047Z"
    description: A helm chart for deploying the cluster lifecycle
    digest: ca86352e640f9cbc21639825b8897ae34b447bf4f38e1b5de7280e91af57faab
    keywords:
    - IcpClusterResource
    - Commercial
    - ICP
    - IKS
    - ICPRHOCP
    - Operations
    - amd64
    - ppc64le
    - s390x
    kubeVersion: '>=1.11.0'
    name: rcm
    urls:
    - http://multiclusterhub-repo:3000/charts/rcm-3.5.0.tgz
    version: 3.5.0
  search-prod:
  - apiVersion: v1
    appVersion: 3.4.0
    created: "2020-03-19T19:51:03.517230368Z"
    description: Helm chart to install the Multicloud Search service
    digest: 02f05bd309942e5c3c2d643f77bd735bca9a291cfc0165363fe10a95526cd01b
    icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png
    keywords:
    - RHOCP
    - ICPRHOCP
    - multicloud
    - multicluster
    - search
    - amd64
    - runtime
    kubeVersion: '>=1.10.0'
    name: search-prod
    urls:
    - http://multiclusterhub-repo:3000/charts/search-prod-3.5.0.tgz
    version: 3.5.0
  topology:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2020-03-19T19:51:03.517658978Z"
    description: helm chart for multicloud topology
    digest: eaac997ca92acbaeea9492a1a02d2953e2c57a620af5bf6971ce32c14c1fd100
    keywords:
    - mcm
    - topology
    kubeVersion: '>=1.10.0'
    name: topology
    urls:
    - http://multiclusterhub-repo:3000/charts/topology-1.0.0.tgz
    version: 1.0.0
generated: "2020-03-19T19:51:03.499839345Z"
